//
//  ClipboardMonitor.swift
//  AnyPaste
//

import AppKit
import CryptoKit
import Foundation

enum ClipboardPayload: Equatable, Sendable {
    enum ImageFormat: String, Equatable, Sendable {
        case png
        case tiff

        fileprivate var pasteboardType: NSPasteboard.PasteboardType {
            switch self {
            case .png:
                return .png
            case .tiff:
                return .tiff
            }
        }
    }

    case text(String)
    case image(data: Data, format: ImageFormat)
    case file(URL)

    var fingerprint: String {
        var hasher = SHA256()

        switch self {
        case .text(let text):
            hasher.update(data: Data("text\u{0}".utf8))
            hasher.update(data: Data(text.utf8))

        case .image(let data, let format):
            hasher.update(data: Data("image\u{0}\(format.rawValue)\u{0}".utf8))
            hasher.update(data: data)

        case .file(let url):
            hasher.update(data: Data("file\u{0}".utf8))
            hasher.update(data: Data(url.standardizedFileURL.absoluteString.utf8))
        }

        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}

@MainActor
final class ClipboardMonitor {
    typealias ChangeHandler = (ClipboardPayload) -> Void

    private struct SuppressedWrite {
        let fingerprint: String
        let expiresAt: Date
    }

    private let pasteboard: NSPasteboard
    private let pollingInterval: TimeInterval
    private let suppressionInterval: TimeInterval

    private var timer: Timer?
    private var lastChangeCount: Int
    private var suppressedWrite: SuppressedWrite?
    private var changeHandler: ChangeHandler?

    private static let sensitivePasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword")
    ]
    private static let remotePayloadMarkerType = NSPasteboard.PasteboardType(
        "com.kotlinsun.anypaste.remote-payload"
    )

    init(
        pasteboard: NSPasteboard = .general,
        pollingInterval: TimeInterval = 1.0,
        suppressionInterval: TimeInterval = 3.0
    ) {
        self.pasteboard = pasteboard
        self.pollingInterval = max(0.1, pollingInterval)
        self.suppressionInterval = max(1.0, suppressionInterval)
        lastChangeCount = pasteboard.changeCount
    }

    deinit {
        timer?.invalidate()
    }

    var isMonitoring: Bool {
        timer != nil
    }

    func start(onChange: @escaping ChangeHandler) {
        changeHandler = onChange
        lastChangeCount = pasteboard.changeCount

        guard timer == nil else { return }

        let timer = Timer(timeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pollPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        changeHandler = nil
        suppressedWrite = nil
    }

    /// Writes an item received from another device without reporting that write
    /// back through `onChange` on the next polling pass.
    @discardableResult
    func writeRemotePayload(_ payload: ClipboardPayload) -> Bool {
        if case .file(let url) = payload, !url.isFileURL {
            return false
        }

        let didWrite: Bool

        pasteboard.clearContents()

        switch payload {
        case .text(let text):
            didWrite = pasteboard.setString(text, forType: .string)

        case .image(let data, let format):
            didWrite = pasteboard.setData(data, forType: format.pasteboardType)

        case .file(let url):
            didWrite = pasteboard.writeObjects([url as NSURL])
        }

        if didWrite {
            _ = pasteboard.setData(
                Data(payload.fingerprint.utf8),
                forType: Self.remotePayloadMarkerType
            )
            suppressedWrite = SuppressedWrite(
                fingerprint: payload.fingerprint,
                expiresAt: Date().addingTimeInterval(suppressionInterval)
            )
        }

        return didWrite
    }

    private func pollPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard let payload = readPayload() else {
            discardExpiredSuppression()
            return
        }

        if shouldSuppress(payload) {
            return
        }

        changeHandler?(payload)
    }

    private func readPayload() -> ClipboardPayload? {
        if pasteboard.types?.contains(Self.remotePayloadMarkerType) == true {
            return nil
        }

        if pasteboard.types?.contains(where: Self.sensitivePasteboardTypes.contains) == true {
            return nil
        }

        if let objects = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) {
            for object in objects {
                guard let nsURL = object as? NSURL else { continue }
                let url = nsURL as URL
                if url.isFileURL {
                    return .file(url)
                }
            }
        }

        if let pngData = pasteboard.data(forType: .png) {
            return .image(data: pngData, format: .png)
        }

        if let tiffData = pasteboard.data(forType: .tiff) {
            return .image(data: tiffData, format: .tiff)
        }

        if let text = pasteboard.string(forType: .string) {
            return .text(text)
        }

        return nil
    }

    private func shouldSuppress(_ payload: ClipboardPayload) -> Bool {
        guard let suppressedWrite else { return false }

        self.suppressedWrite = nil
        guard suppressedWrite.expiresAt >= Date() else { return false }
        return suppressedWrite.fingerprint == payload.fingerprint
    }

    private func discardExpiredSuppression() {
        guard let suppressedWrite, suppressedWrite.expiresAt < Date() else { return }
        self.suppressedWrite = nil
    }
}
